<!--
Copyright 2021 Province of British Columbia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
-->


---
title: "Census PUMF"
output: html_notebook
---


Uses the 2016 Census PUMF file

```{r setup}
# tidyverse
library(tidyverse)
library(haven)

# other utilities

```


## Individual file

```{r}

d_indiv <- haven::read_spss(here::here("data", "_Individual_98M0001X", "data_donnees_2016_ind.sav"))

head(d_indiv)

write_rds(d_indiv, here::here("data", "_Individual_98M0001X", "d_indiv.rds"))

```



## Hierarchical file

```{r}

d_hierarch <- haven::read_spss(here::here("data", "_Hierachical File", "data_donnees_2016_hier.sav"))

head(d_hierarch)

```

